apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: demo
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - demo.keptn-demo-dev.svc.cluster.local
  - demo
  http:
  - route:
    - destination:
        host: demo.keptn-demo-dev.svc.cluster.local
