apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: app-ingress
spec:
  rules:
    - host: {{ .Values.keptn.stage }}-app.krateoplatformops.io
      http:
        paths:
          - backend:
              serviceName: demo
              servicePort: 80
